### ISSUE TITLE
make default_image in presets optional when UEFI is used

### ISSUE THREAD

**Issue by gdamjan** [archlinux/mkinitcpio#77]
When building unified UEFI images with `mkinitcpio --uefi /tmp/test.efi`, mkinitcpio will create (and later remove) a **temporary** initcpio image (`/tmp/mkinitcpio.dJk7yP`).

On the other hand, in preset files, the `default_image` parameter is mandatory, even though `default_efi_image="/boot/EFI/Linux/archlinux-linux.efi"` is used.

For ex:
```
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> WARNING: No image file specified. Skipping image `default'
```

I suggest that if `default_efi_image=` is set, `default_image=` should be optional. Thoughts?

**Comment by Foxboron** [comment]
I think this is reasonable. It shouldn't be super complicated to implement and I can mock up something unless anyone else want a fairly easy contribution :)?

**Comment by H5117** [comment]
I think the complete solution should also avoid installing a kernel (f.ex. /boot/vmlinuz-linux). I. e. ideally two modes should be implemented:
- installing configured kernels and generating configured initramfs images for each of them (default, because allows to declare binutils and sbsigntools as optional dependencies)
- generating combined efi executables (with configured kernels, initramfs images, parameters and splash images), optionally signed.

Currently mkinitcpio installs available kernels unconditionally, what also wastes space.

**Comment by gdamjan** [comment]
> I think the complete solution should also avoid installing a kernel (f.ex. /boot/vmlinuz-linux).

I agree, but one by one :)

I'd also suggest that the kernel package has a symlink from /usr/share/kernels/<pkgver> -> /usr/lib/modules/<kver> (because they are not the same) - that would simplify a lot of scripts.

**Comment by rulim34** [comment]
Any updates on this?

Waiting this to be implemented since I want to add more kernel but my EFI partition is full.

**Comment by gdamjan** [comment]
🤷

**Comment by gdamjan** [comment]
> A decent workaround is to simply write the images into your root partition, and only write the UEFI binaries into your EFI partition. I haven't had any problems with this workaround yet.

that's the current behaviour (assuming /boot is not on EFI)

**Comment by AlexApps99** [comment]
You can't really assume that sort of thing though, as comments mentioning /boot had EFI mounted to it, or at the very least, all files saved to EFI partition

**Comment by Foxboron** [comment]
Fixed with https://github.com/archlinux/mkinitcpio/pull/99
